### ISSUE TITLE
my free can't create a standard (NC base) DLVM

### ISSUE THREAD

**Issue by marcolin1215** [MicrosoftDocs/azure-docs.zh-tw#104]
Hi Sir,
I want to try my ML program on DLVM with my free account.
My account still has NT6000 points.
But it shows Validation failed. 
QuotaExceededOperation results in exceeding quota limits of Core. Maximum allowed: 4, Current in use: 0, Additional requested: 6. 
Is it passable to provide a trial for me?

Thank you
Marco

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3fcbdad5-24a1-a4a7-4b36-a4fd42935670
* Version Independent ID: 70226c0b-6ef7-a6fd-0c8a-d021d1090ea5
* Content: [在 Azure 上佈建深入學習資料科學虛擬機器](https://docs.microsoft.com/zh-tw/azure/machine-learning/data-science-virtual-machine/provision-deep-learning-dsvm)
* Content Source: [articles/machine-learning/data-science-virtual-machine/provision-deep-learning-dsvm.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/machine-learning/data-science-virtual-machine/provision-deep-learning-dsvm.md)
* Service: **machine-learning**
* GitHub Login: @gopitk
* Microsoft Alias: **gokuma**

**Comment by LisandroSu** [comment]
Hello, @marcolin1215  
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team 
 
Hi @SunnyDeng, can you check this issue and help them out? Thanks!

**Comment by marcolin1215** [comment]
Thanks for reply. I will try to feedback to product service.
