### ISSUE TITLE
Please correct the Chinese translation of 'Pay-as-you-go'

### ISSUE THREAD

**Issue by StellaSSHuang** [MicrosoftDocs/azure-docs.zh-tw#105]
Pay-as-you-go should be '隨用隨付型', not '預付型', please correct the title on the left-side bar title.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: c2e8e7be-d772-b6a5-c662-0d3ef0095ef5
* Version Independent ID: 4fc59997-63c3-229d-bf09-1c095c0e7a1b
* Content: [了解隨用隨付訂用帳戶的 Azure 保留執行個體使用量](https://docs.microsoft.com/zh-tw/azure/billing/billing-understand-reserved-instance-usage)
* Content Source: [articles/billing/billing-understand-reserved-instance-usage.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/billing/billing-understand-reserved-instance-usage.md)
* Service: **billing**
* GitHub Login: @manish-shukla01
* Microsoft Alias: **manshuk**

**Comment by LisandroSu** [comment]
Hello, @StellaSSHuang , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @StellaSSHuang , 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
