### ISSUE TITLE
我是云碩科技Jeff

### ISSUE THREAD

**Issue by guessleej** [MicrosoftDocs/azure-docs.zh-tw#109]
請問為什麼不能監控VMware了
我們很需要這個功能

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 722cdf93-af91-26ac-697a-f090134a71a2
* Version Independent ID: 1b4085ee-0c27-b620-3b4a-8ec4a2707b32
* Content: [Log Analytics 中的 VMware 監視解決方案](https://docs.microsoft.com/zh-tw/azure/log-analytics/log-analytics-vmware)
* Content Source: [articles/log-analytics/log-analytics-vmware.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/log-analytics/log-analytics-vmware.md)
* Service: **log-analytics**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by LisandroSu** [comment]
您好，@guessleej

非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。 

請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。 

若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。 

我們由衷感謝您對文章的貢獻。  

順頌時祺 
Microsoft DOCS 國際小組
