### ISSUE TITLE
"Pay-as-you-go" should be "隨用隨付"

### ISSUE THREAD

**Issue by StellaSSHuang** [MicrosoftDocs/azure-docs.zh-tw#110]
所有英文原文是"Pay-as-you-go"的部份，中文都應該是"隨用隨付"，而不是"預付型"。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: b15d245b-92f1-785d-2776-ebec6a4fad42
* Version Independent ID: 2ac3df93-eed6-76f6-e356-2401c57403fa
* Content: [什麼是 Azure 保留？](https://docs.microsoft.com/zh-tw/azure/billing/billing-save-compute-costs-reservations#feedback)
* Content Source: [articles/billing/billing-save-compute-costs-reservations.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/billing/billing-save-compute-costs-reservations.md)
* Service: **billing**
* GitHub Login: @yashesvi
* Microsoft Alias: **yashar**

**Comment by StellaSSHuang** [comment]
It should be "隨用隨付" for all "Pay-as-you-go", it's not "預付型".

**Comment by LisandroSu** [comment]
您好 @StellaSSHuang ， 

 謝謝您的寶貴意見。 

 我們目前正在檢閱您的留言，將會盡快與您連絡。 

 順頌時祺 
Microsoft DOCS 國際小組

**Comment by LisandroSu** [comment]
您好 @StellaSSHuang ，

謝謝您的寶貴意見。

我們目前正在檢閱您的留言，將會盡快與您連絡。

順頌時祺
Microsoft DOCS 國際小組

**Comment by CeciAc** [comment]
您好，@StellaSSHuang，  
謝謝您的寶貴意見。 
我們的編審小組審閱了您提出的語言建議，並接受了這些建議。我們已實作您的意見反應並發佈至 Docs 網站上已更新文章的以下頁面 XXX。  
我們由衷感謝您對文章的貢獻，並期望您繼續提供寶貴的意見。 
順頌時祺 
Microsoft DOCS 國際小組

**Comment by StellaSSHuang** [comment]
Hi Team,

There is one you forgot to fix.
[cid:image001.jpg@01D46610.064D34E0]



Cheers,
Stella | Azure Subscription Management Support, ASMS

**Comment by StellaSSHuang** [comment]
Hi Team,

There is one on left hand title you forgot to fix. It should be "隨用隨付型方案使用量", not "預付型方案使用量".

Stella
