### ISSUE TITLE
Fail to install Microsoft.Azure.CognitiveServices.Vision.Face 2.2.0-preview

### ISSUE THREAD

**Issue by WilliamLINWEN** [MicrosoftDocs/azure-docs.zh-tw#126]
I got the error message

Install-Package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
位於 線路:1 字元:2
+  Install-Package Microsoft.Azure.CognitiveServices.Vision.Face -Versi ...
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 31a7905f-5818-4398-ee39-2842519dc054
* Version Independent ID: 7f6a714b-cd88-694e-fd31-ad96fdfe5ed3
* Content: [教學課程：搭配使用 .NET SDK 和 C# 來偵測並框出影像中的人臉 - Azure Cognitive Services](https://docs.microsoft.com/zh-tw/azure/cognitive-services/face/tutorials/faceapiincsharptutorial)
* Content Source: [articles/cognitive-services/Face/Tutorials/FaceAPIinCSharpTutorial.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/cognitive-services/Face/Tutorials/FaceAPIinCSharpTutorial.md)
* Service: **cognitive-services**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by CeciAc** [comment]
您好，@WilliamLINWEN， 
非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。 
請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。 
若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。 
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
