### ISSUE TITLE
Unable to connect with "Twitter and sentiment"

### ISSUE THREAD

**Issue by boulegit** [MicrosoftDocs/azure-docs.zh-tw#127]
Unable to connect with "Twitter and sentiment"

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: ae1a4055-33b7-eead-6eb4-0092b7112567
* Version Independent ID: 7b866c4b-46d2-d420-278e-f49ec05e5d0d
* Content: [建立與 Azure Logic Apps 整合的函式](https://docs.microsoft.com/zh-tw/azure/azure-functions/functions-twitter-email)
* Content Source: [articles/azure-functions/functions-twitter-email.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/azure-functions/functions-twitter-email.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by LisandroSu** [comment]
Hello, @boulegit 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
