### ISSUE TITLE
將您的 LUIS 應用程式連線至 Bot的問題

### ISSUE THREAD

**Issue by chao1017** [MicrosoftDocs/azure-docs.zh-tw#128]
在「將您的 LUIS 應用程式連線至 Bot」這一段的說明，在現在的Azure Portal中找不到LUIS的相關設定項目，請問是自行在「Application settings」新增？

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: d788e575-9dac-1824-d706-6f25c2b56bb8
* Version Independent ID: 9eb2b452-da24-477f-c843-f0109109fd0b
* Content: [使用 C# 的 LUIS Bot - Web 應用程式 Bot - Bot Framework SDK 3.0 - Azure Cognitive Services](https://docs.microsoft.com/zh-tw/azure/cognitive-services/luis/luis-csharp-tutorial-build-bot-framework-sample#connect-your-luis-app-to-the-bot)
* Content Source: [articles/cognitive-services/LUIS/luis-csharp-tutorial-build-bot-framework-sample.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/cognitive-services/LUIS/luis-csharp-tutorial-build-bot-framework-sample.md)
* Service: **cognitive-services**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by LisandroSu** [comment]
您好，@chao1017

非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。 

請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。 

若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。 

我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
