### ISSUE TITLE
Meet trouble when do curl command AFTER DEPLOYED according to the tutorial

### ISSUE THREAD

**Issue by Frankie34** [MicrosoftDocs/azure-docs.zh-tw#259]
After deployed the java function, the curl command should be following 
And the function key can be found in the "Function Apps/Functions/Manage" slot from "Home/Resource groups/ java-functions-group/{your function name} page at Azure portal
```
curl "https://fabrikam-function-20170920120101928.azurewebsites.net/api/hello&code={your function key}"

```

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: e656bde5-b5d8-8d80-b7b3-ab430e57613e
* Version Independent ID: 329eb12f-7302-4ecf-c1bf-a50ba3f34bdf
* Content: [使用 Java 和 Maven 在 Azure 中建立第一個函式](https://docs.microsoft.com/zh-tw/azure/azure-functions/functions-create-first-java-maven)
* Content Source: [articles/azure-functions/functions-create-first-java-maven.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/azure-functions/functions-create-first-java-maven.md)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw, glenga**

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback/提供產品意見反應" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
