### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andyjuang840502** [MicrosoftDocs/azure-docs.zh-tw#262]
$snapshotConfig = New-AzSnapshotConfig -SourceResourceId $snapshot.Id -Location $snapshot.Location -CreateOption Copy -SkuName Standard_LRS
這行的skuname那邊應該是輸入StandardLRS而非Standard_LRS

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: aaf8069a-d18b-a8b2-be13-0025059a22dd
* Version Independent ID: 127759a9-8f34-525f-c4d5-43d30d61d60d
* Content: [Azure PowerShell 指令碼範例 - 將受控磁碟快照集複製 (移動) 到相同或不同的訂用帳戶](https://docs.microsoft.com/zh-tw/azure/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-snapshot-to-same-or-different-subscription#feedback)
* Content Source: [articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-snapshot-to-same-or-different-subscription.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/virtual-machines/scripts/virtual-machines-windows-powershell-sample-copy-snapshot-to-same-or-different-subscription.md)
* Service: **virtual-machines-windows**
* GitHub Login: @ramankumarlive
* Microsoft Alias: **ramankum**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #27716](https://github.com/MicrosoftDocs/azure-docs/issues/27716) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@andyjuang840502 

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 -  https://github.com/MicrosoftDocs/azure-docs/issues/27716

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
