### ISSUE TITLE
取得參數問題

### ISSUE THREAD

**Issue by andy840119** [MicrosoftDocs/azure-docs.zh-tw#263]
我要從Azure的後台的哪邊去取得下面的這些參數?
(s_eventHubsCompatibleEndpoint)使用先前所記錄的事件中樞相容端點來取代變數的值。
(s_eventHubsCompatiblePath)使用先前所記錄的事件中樞相容路徑來取代變數的值。
(s_iotHubSasKey)使用先前所記錄的 iothubowner 主要金鑰來取代變數的值。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 666d1390-a995-fb5f-e1ee-49e28c50e901
* Version Independent ID: d699e566-83d8-5af9-56a5-4baa56ae0455
* Content: [將遙測傳送至 Azure IoT 中樞快速入門 (C#)](https://docs.microsoft.com/zh-tw/azure/iot-hub/quickstart-send-telemetry-dotnet#feedback)
* Content Source: [articles/iot-hub/quickstart-send-telemetry-dotnet.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/iot-hub/quickstart-send-telemetry-dotnet.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robin.shahan**

**Comment by CeciAc** [comment]
你好，@andy840119
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
