### ISSUE TITLE
Translation request

### ISSUE THREAD

**Issue by yuchiehchang** [MicrosoftDocs/azure-docs.zh-tw#266]
"Pay-As-You-Go" is "隨用隨付" in Traditional Chinese. But in some sections of article, it's translated to 預付型.
Please help to update for it.
Thank you!

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 59edbf44-87b8-7b7a-92a5-6ba12bdd8aff
* Version Independent ID: 1d7974d8-a0f2-e2b1-cc38-565e2d7fec40
* Content: [了解 Azure 成本管理資料](https://docs.microsoft.com/zh-tw/azure/cost-management/understand-cost-mgt-data#feedback)
* Content Source: [articles/cost-management/understand-cost-mgt-data.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/cost-management/understand-cost-mgt-data.md)
* Service: **cost-management**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by CeciAc** [comment]
Hello, @yuchiehchang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yuchiehchang

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yuchiehchang 

Thank you for your feedback and suggestion.  

The file is currently under localization process. We will release this article soon.
Many thanks for your support. 

Kind regards,

Microsoft DOCS Global Experience Team
