### ISSUE TITLE
Fix Step 2: Bind SSL

### ISSUE THREAD

**Issue by t106362512** [MicrosoftDocs/azure-docs.zh-tw#267]
If SSL Cipher doesn't set the "AES128-SHA", it can't not working.
https://i.imgur.com/xY0o5tl.png

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 77a94e6f-a799-494f-f2f9-171c1804e5f4
* Version Independent ID: 0ca5e2ae-5889-61ef-3ce7-5c447f7519a6
* Content: [設定 SSL 連線能力，以安全地連線到適用於 MySQL 的 Azure 資料庫](https://docs.microsoft.com/zh-tw/azure/mysql/howto-configure-ssl#step-2-bind-ssl)
* Content Source: [articles/mysql/howto-configure-ssl.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/mysql/howto-configure-ssl.md)
* Service: **mysql**
* GitHub Login: @ajlam
* Microsoft Alias: **andrela**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #28990](https://github.com/MicrosoftDocs/azure-docs/issues/28990) via [**ZenHub**](https://www.zenhub.com/)
