### ISSUE TITLE
Please verify if Service Administrator will lose access after change directory

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#279]
Please verify if Service Administrator will lose access after change directory. Service Administrator shouldn't lose access after change directory. Thank you.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: da261ee4-3348-b520-a27c-98f9d9ef40cc
* Version Independent ID: 13d12189-ee46-8058-dd99-058adc69f1c5
* Content: [將現有的 Azure 訂用帳戶新增至您的租用戶 - Azure Active Directory](https://docs.microsoft.com/zh-tw/azure/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory#feedback)
* Content Source: [articles/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/active-directory/fundamentals/active-directory-how-subscriptions-associated-directory.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
Hello, @HannahHsiao

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by HannahHsiao** [comment]
Hello, @CeciAc, 

The doc is incorrect. The Service Administrator won't lose access after change directory.

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30558](https://github.com/MicrosoftDocs/azure-docs/issues/30558) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @HannahHsiao

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/30558

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
