### ISSUE TITLE
How to install IoT edge runtime on Linux openwrt

### ISSUE THREAD

**Issue by edenhuang0610** [MicrosoftDocs/azure-docs.zh-tw#286]
Hi,

There is a requirement for installing IoT edge runtime on LINUX openwrt device.
As the below steps, we cannot use "dpkg" to install .deb files. 

Can we install IoT edge runtime on openwrt? How to install it?
Please provide more details.
Thanks!

# Download and install the moby-engine
curl -L https://aka.ms/moby-engine-armhf-latest -o moby_engine.deb && sudo dpkg -i ./moby_engine.deb

# Download and install the moby-cli
curl -L https://aka.ms/moby-cli-armhf-latest -o moby_cli.deb && sudo dpkg -i ./moby_cli.deb

# Run apt-get fix
sudo apt-get install -f

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 1cf7aade-9690-1b15-edca-952e4f509601
* Version Independent ID: b99f0f0f-87fe-5446-670e-b3fd8eb1c34d
* Content: [在 Linux ARM32 上安裝 Azure IoT Edge](https://docs.microsoft.com/zh-tw/azure/iot-edge/how-to-install-iot-edge-linux-arm)
* Content Source: [articles/iot-edge/how-to-install-iot-edge-linux-arm.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/iot-edge/how-to-install-iot-edge-linux-arm.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
Hello, @edenhuang0610 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
