### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by Ianwu0812** [MicrosoftDocs/azure-docs.zh-tw#337]
I followed the guide to access node in AKS. This guide looks perfect, but the final step have some problem, I can not SSH to node in AKS, even I get the IP , setup the public key, and run a container as SSH client by following the guide.

Error message is:

```
Permission denied (publickey).
```
---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3b81a147-db1c-b92f-88d1-6dd0991a72fe
* Version Independent ID: f5a2c949-498f-5848-d89c-031d1a757120
* Content: [透過 SSH 連線至 Azure Kubernetes Service (AKS) 叢集](https://docs.microsoft.com/zh-tw/azure/aks/ssh#feedback)
* Content Source: [articles/aks/ssh.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/aks/ssh.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
Hello, @Ianwu0812

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
