### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by goder7015** [MicrosoftDocs/azure-docs.zh-tw#351]
區域與端點 下方注意處的網址結構有誤，請將重複部分的url刪除

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 11673bc9-9062-278d-c5b8-84b05f2b81be
* Version Independent ID: 29347a63-de63-4ff0-5a62-149ab31d1b7e
* Content: [語音轉換文字 API 參考 (REST)-語音服務 - Azure Cognitive Services](https://docs.microsoft.com/zh-tw/azure/cognitive-services/speech-service/rest-speech-to-text#next-steps)
* Content Source: [articles/cognitive-services/Speech-Service/rest-speech-to-text.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/cognitive-services/Speech-Service/rest-speech-to-text.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by CeciAc** [comment]
@goder7015  您好：
我們由衷感謝您的寶貴意見，並將竭盡全力改進您在 docs.microsoft.com 的體驗。在此之前，我們還需要更多的資訊，才能落實您的意見反應。可否請您提供更多的詳細資料，進一步說明您的意見？
順頌時祺
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@goder7015  您好：
我們仍在持續關注您先前所提供的寶貴意見，但我們還需要更多的資訊，才能落實您的意見反應。可否請您提供更多的詳細資料，進一步說明您的意見？
順頌時祺
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@goder7015 您好：
再次感謝您的寶貴意見。
很遺憾至今我們仍未收到您的進一步資訊，所以無法處理您的意見反應。目前我們會先將此 GitHub 問題結案處理，期望您日後能夠再提供更多的意見。
順頌時祺
Microsoft DOCS International Team
