### ISSUE TITLE
缺少下載support plan invoice的方式

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#379]
缺少下載support plan invoice的方式

---
#### 文件的詳細資料

⚠ *請勿編輯此部分。 docs.microsoft.com 必要 ➟ 連結 GitHub 問題。*

* ID: 4ce159af-25d8-dbf9-f805-325b4efc04ac
* Version Independent ID: e64078cb-075a-a6cf-775f-0754fd6395f5
* Content: [下載 Azure 帳單發票和每日使用量資料](https://docs.microsoft.com/zh-hk/azure/billing/billing-download-azure-invoice-daily-usage-date)
* Content Source: [articles/billing/billing-download-azure-invoice-daily-usage-date.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/billing/billing-download-azure-invoice-daily-usage-date.md)
* Service: **billing**
* GitHub Login: @genlin
* Microsoft Alias: **banders**

**Comment by CeciAc** [comment]
您好，@HannahHsiao
非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。 
請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。 
若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。 
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
