### ISSUE TITLE
缺少取消support plan的方式

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#380]
缺少取消support plan的方式

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 576cae7d-f9e6-72ef-c6ba-d5a4e359d70d
* Version Independent ID: af78deae-d409-6261-a817-b504965d1988
* Content: [取消 Azure 訂用帳戶](https://docs.microsoft.com/zh-tw/azure/billing/billing-how-to-cancel-azure-subscription)
* Content Source: [articles/billing/billing-how-to-cancel-azure-subscription.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/billing/billing-how-to-cancel-azure-subscription.md)
* Service: **billing**
* GitHub Login: @genlin
* Microsoft Alias: **banders**

**Comment by CeciAc** [comment]
您好，@HannahHsiao
非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。 
請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。 
若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。 
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
