### ISSUE TITLE
Microsoft.CognitiveServices.Speech Not Found

### ISSUE THREAD

**Issue by jamesbang** [MicrosoftDocs/azure-docs.zh-tw#495]
我匯入了 Microsoft.CognitiveServices.Speech.1.6.0.unitypackage，但是在範例程式中，using Microsoft.CognitiveServices.Speech，無法找到該 packange

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 9a888c93-e3a8-7c09-b040-3539cf494047
* Version Independent ID: 569cdd49-7add-950c-00ce-bb1b730243ca
* Content: [快速入門：辨識語音 (Unity) - 語音服務 - Azure Cognitive Services](https://docs.microsoft.com/zh-tw/azure/cognitive-services/speech-service/quickstart-csharp-unity#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstart-csharp-unity.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/cognitive-services/Speech-Service/quickstart-csharp-unity.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by zhouwangzw** [comment]
Hello, 

sorry to hear that the quick start does not work for you. What is the platform you are using with Unity, Windows or Android? 

Might discussion in Speech Sample repository on Github be also helpful to resolve your issues? https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues?utf8=%E2%9C%93&q=is%3Aissue+unity 

Thanks,

**Comment by srvbpigh** [comment]
Hello, @jamesbang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by jamesbang** [comment]
i use Unity for Mac, i must trans to Unity for Windows？

**Comment by wolfma61** [comment]
Unity currently is not supported on Mac

**Comment by jamesbang** [comment]
ok~ i trans to Unity on Windows try again~thanks.

**Comment by CeciAc** [comment]
Hello, @jamesbang 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team

**Comment by wolfma61** [comment]
@jamesbang - for non documentation related question I recommend the 'Speech SDK Samples' github project.
https://github.com/Azure-Samples/cognitive-services-speech-sdk  

Wolfgang

**Comment by jamesbang** [comment]
Hello

I use Unity on Windows, it works.
