### ISSUE TITLE
github連結失效

### ISSUE THREAD

**Issue by BookHsu** [MicrosoftDocs/azure-docs.zh-tw#517]
https://docs.microsoft.com/zh-tw/azure/notification-hubs/notification-hubs-aspnet-backend-windows-dotnet-wns-notification
![圖片](https://user-images.githubusercontent.com/29597478/63085144-69e6dc80-bf7f-11e9-9a4c-ab6b5f97e2f5.png)

![圖片](https://user-images.githubusercontent.com/29597478/63085162-7408db00-bf7f-11e9-9a3b-06fc8c06901b.png)

**Comment by srvbpigh** [comment]
Hello, @BookHsu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #37174](https://github.com/MicrosoftDocs/azure-docs/issues/37174) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
您好，@BookHsu

非常感謝您的貢獻。您的意見反應與原始文件相關。
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態   - https://github.com/MicrosoftDocs/azure-docs/issues/37174
我們由衷感謝您對文章的貢獻。
順頌時祺
Microsoft DOCS 國際小組
