### ISSUE TITLE
Cannot find "Aspera" in marketplace

### ISSUE THREAD

**Issue by juchen0411** [MicrosoftDocs/azure-docs.zh-tw#527]
Hi, I cannot find Aspera in marketplace nor CSP portal, can you confirm if this product can be purchased on Azure?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3eb2de75-14a2-f63b-359e-314659094082
* Version Independent ID: 3ff6f513-2d1a-efde-c802-e33f4f0f0196
* Content: [使用 Aspera 將檔案上傳至 Azure 媒體服務帳戶](https://docs.microsoft.com/zh-tw/azure/media-services/previous/media-services-upload-files-with-aspera#feedback)
* Content Source: [articles/media-services/previous/media-services-upload-files-with-aspera.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/media-services/previous/media-services-upload-files-with-aspera.md)
* Service: **media-services**
* GitHub Login: @johndeu
* Microsoft Alias: **juliako**

**Comment by srvbpigh** [comment]
Hello, @juchen0411
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @juchen0411

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
