### ISSUE TITLE
關於偵測人臉的部分

### ISSUE THREAD

**Issue by miller80531** [MicrosoftDocs/azure-docs.zh-tw#532]
在執行偵測人臉部分的程式碼時，會出現''NameError: name 'CognitiveServicesCredentials' is not defined''的錯誤訊息。想請問這部分是哪個環節出的錯，謝謝各位!

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: e458d65d-3c89-3e41-fdf7-613523fcc78a
* Version Independent ID: 4ca7bedf-6435-d19d-9a47-fa0a686da00c
* Content: [快速入門：使用 Python SDK 來偵測並框出影像中的臉部 - Azure Cognitive Services](https://docs.microsoft.com/zh-tw/azure/cognitive-services/face/tutorials/faceapiinpythontutorial#feedback)
* Content Source: [articles/cognitive-services/Face/Tutorials/FaceAPIinPythonTutorial.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/cognitive-services/Face/Tutorials/FaceAPIinPythonTutorial.md)
* Service: **cognitive-services**
* Sub-service: **face-api**
* GitHub Login: @SteveMSFT
* Microsoft Alias: **sbowles**

**Comment by srvbpigh** [comment]
Hello, @miller80531
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
您好，@miller80531
非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。 
請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。 
若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。 
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
