### ISSUE TITLE
UI need to be updated

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#536]
UI need to be updated

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 43a60f94-0826-8cdf-04b3-c5f20d299720
* Version Independent ID: 7d1dcfe7-4e68-6b98-1003-9154e7a0b22d
* Content: [如何建立 Azure 支援要求](https://docs.microsoft.com/zh-tw/azure/azure-supportability/how-to-create-azure-support-request)
* Content Source: [articles/azure-supportability/how-to-create-azure-support-request.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/azure-supportability/how-to-create-azure-support-request.md)
* Service: **azure-supportability**
* GitHub Login: @ganganarayanan
* Microsoft Alias: **gangan**

**Comment by srvbpigh** [comment]
Hello, @HannahHsiao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @HannahHsiao
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @HannahHsiao
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @HannahHsiao 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
