### ISSUE TITLE
請問"訂用帳戶的帳戶管理員是誰？" 步驟在哪裡?

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#543]
舊版文件有 "訂用帳戶的 帳戶 管理員是誰？"步驟，但新版只有 "帳戶的 帳單 管理員是誰？"，
請添加
帳戶管理員就是註冊或購買 Azure 訂閱的人員。 他們已獲得授權存取帳戶中心並可執行各種管理工作，像是建立訂用帳戶、取消訂用帳戶、變更訂用帳戶的計費方式，或變更服務管理員。 如果您不確定誰是訂用帳戶的帳戶管理員，請使用下列步驟來找出帳戶管理員。
	1. 瀏覽 Azure 入口網站中的 [訂用帳戶] 頁面。
	2. 選取您想要檢查的訂用帳戶，然後查看 [設定]。
	3. 選取 [屬性] 。 該訂用帳戶的帳戶管理員會顯示在 [帳戶管理員] 方塊中。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 65b8cd29-3c9b-6afc-d4fb-256463776002
* Version Independent ID: d905e8f9-49c6-19de-1c43-796efc04003f
* Content: [將 Azure 訂用帳戶的帳單擁有權轉移給另一個帳戶](https://docs.microsoft.com/zh-tw/azure/billing/billing-subscription-transfer#feedback)
* Content Source: [articles/billing/billing-subscription-transfer.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/billing/billing-subscription-transfer.md)
* Service: **billing**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @HannahHsiao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #39049](https://github.com/MicrosoftDocs/azure-docs/issues/39049) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
您好，@HannahHsiao
非常感謝您的貢獻。您的意見反應與原始文件相關。 
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/azure-docs/issues/39049
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
