### ISSUE TITLE
The Python code for 部署到雲端 is wrong

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#553]
The Python code for 部署到雲端 is wrong https://docs.microsoft.com/zh-tw/azure/machine-learning/service/how-to-deploy-fpga-web-service#deploy-to-the-cloud

it should be specify the region for the AKS provisioning
prov_config = AksCompute.provisioning_configuration(vm_size = "Standard_PB6s",
                                                    agent_count = 1, 
                                                    location = " southeastasia")

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 25565324-f64d-a8db-bc1c-e50956e6e878
* Version Independent ID: a6c9ffa3-c085-b4fc-7153-06adb8a50ce4
* Content: [什麼是 FPGA-如何部署 - Azure Machine Learning](https://docs.microsoft.com/zh-tw/azure/machine-learning/service/how-to-deploy-fpga-web-service)
* Content Source: [articles/machine-learning/service/how-to-deploy-fpga-web-service.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/machine-learning/service/how-to-deploy-fpga-web-service.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @tedway
* Microsoft Alias: **tedway**

**Comment by srvbpigh** [comment]
Hello, @HannahHsiao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #39407](https://github.com/MicrosoftDocs/azure-docs/issues/39407) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @HannahHsiao

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/39407

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
