### ISSUE TITLE
使用新的Firebase API

### ISSUE THREAD

**Issue by w9wen** [MicrosoftDocs/azure-docs.zh-tw#601]
由於更新到新版，[IntentFilter(new[] { "com.google.firebase.INSTANCE_ID_EVENT" })]這一段應該取消。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 2a03ab5f-3dda-f469-33e0-9504c90d468c
* Version Independent ID: 4f8e4309-cd06-f09f-00f0-d978b3d16777
* Content: [使用 Azure 通知中樞將推播通知傳送至 Xamarin.Android 應用程式](https://docs.microsoft.com/zh-tw/azure/notification-hubs/xamarin-notification-hubs-push-notifications-android-gcm#feedback)
* Content Source: [articles/notification-hubs/xamarin-notification-hubs-push-notifications-android-gcm.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/notification-hubs/xamarin-notification-hubs-push-notifications-android-gcm.md)
* Service: **notification-hubs**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by w9wen** [comment]
否則會出現
java.lang.InstantiationException: java.lang.Class<com.google.firebase.iid.FirebaseInstanceIdReceiver> cannot be instantiated
的錯誤

**Comment by srvbpigh** [comment]
Hello, @w9wen
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
您好，@w9wen 
非常感謝您的貢獻。您的意見反應與原始文件相關。 
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/azure-docs/issues/43753
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
