### ISSUE TITLE
errata report

### ISSUE THREAD

**Issue by MingShyanWei** [MicrosoftDocs/azure-docs.zh-tw#602]
[請在此輸入您的意見]

resourceGroupName="<your-resource-group>"
storageAccountName="<your-storage-account>"

# This command assumes you have logged in with az login
httpEndpoint=$(az storage account show \
    --resource-group $resourceGroupName \
    --name $storageAccountName \
    --query "primaryEndpoints.file" | tr -d '"')
smbPath=$(echo $httpEndpoint | cut -c7-$(expr length $httpEndpoint))
fileHost=$(echo $fileHost | tr -d "/")

nc -zvw3 $fileHost 445

Correction:
......
smbPath=$(echo $httpEndpoint | cut -c7-$(expr length $httpEndpoint))
fileHost=$(echo $smbPath | tr -d "/")
......

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 8d60d83f-0094-6c5e-e105-712c24bf1acc
* Version Independent ID: 594af294-fd5d-a8c7-d456-6d753b7b62f8
* Content: [搭配 Linux 使用 Azure 檔案](https://docs.microsoft.com/zh-tw/azure/storage/files/storage-how-to-use-files-linux)
* Content Source: [articles/storage/files/storage-how-to-use-files-linux.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/storage/files/storage-how-to-use-files-linux.md)
* Service: **storage**
* Sub-service: **files**
* GitHub Login: @roygara
* Microsoft Alias: **rogarana**

**Comment by srvbpigh** [comment]
Hello, @MingShyanWei
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @MingShyanWei 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/azure-docs/issues/44506

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
