### ISSUE TITLE
登入 [其他安全性驗證] 頁面，然後選取 [應用程式密碼]。

### ISSUE THREAD

**Issue by doggy8088** [MicrosoftDocs/azure-docs.zh-tw#605]
我在登入 [其他安全性驗證] 頁面之後，找不到 [應用程式密碼] 的連結！

![image](https://user-images.githubusercontent.com/88981/71541635-2c677680-2997-11ea-9d05-1f17b81c5a70.png)

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 8751595d-4839-d2ee-1e2c-16d07ef84a2d
* Version Independent ID: e66f96b3-5b88-9304-1ec0-9e3bb8a2cfbe
* Content: [如何管理應用程式密碼-Azure Active Directory](https://docs.microsoft.com/zh-tw/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords#create-and-delete-app-passwords-from-the-additional-security-verification-page)
* Content Source: [articles/active-directory/user-help/multi-factor-authentication-end-user-app-passwords.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/active-directory/user-help/multi-factor-authentication-end-user-app-passwords.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
您好，@doggy8088，  

非常感謝您的貢獻。您的意見反應與原始文件相關。  

因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/azure-docs/issues/45360。  

我們由衷感謝您對文章的貢獻。   

順頌時祺  
Microsoft DOCS 國際小組
