### ISSUE TITLE
中文翻譯

### ISSUE THREAD

**Issue by Rudy1021** [MicrosoftDocs/azure-docs.zh-tw#609]
很多地方應該是英文卻被翻成中文
使用原文觀看就沒問題了

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4b8dfa1c-b989-45b0-07a8-9a0beed32e50
* Version Independent ID: c3392c60-1207-5663-45f3-cc447f019e58
* Content: [語言支援-語音服務 - Azure Cognitive Services](https://docs.microsoft.com/zh-tw/azure/cognitive-services/speech-service/language-support#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/language-support.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/cognitive-services/Speech-Service/language-support.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by srvbpigh** [comment]
Hello, @Rudy1021
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@Rudy1021 您好：  
 
感謝您的參與。  

目前不接受參與機器翻譯內容的翻譯問題。  

我們很重視您對人工翻譯內容的意見反應與建議，並使用這些意見來訓練機器翻譯引擎，因此，您的貢獻內容會隨著時間改善人工與機器翻譯的品質。  

您可以根據各個內容檔案標頭的 ms.translationtype 中繼資料值 “HT”，分辨出人工翻譯的主題，其他則是機器翻譯的主題 (值為 “MT” 代表機器翻譯)。  

非常感謝您的支援。  

Microsoft DOCS 全球體驗小組
