### ISSUE TITLE
some cmd not work

### ISSUE THREAD

**Issue by yellow456434** [MicrosoftDocs/azure-docs.zh-tw#612]
In [configure virtual machine scale set-based AKS clusters for SSH access] part.
Have a set SCALE_SET_NAME step. 
when I run this command, the terminal show zsh not found "[0].name "

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 3b81a147-db1c-b92f-88d1-6dd0991a72fe
* Version Independent ID: f5a2c949-498f-5848-d89c-031d1a757120
* Content: [透過 SSH 連線至 Azure Kubernetes Service (AKS) 叢集](https://docs.microsoft.com/zh-tw/azure/aks/ssh#feedback)
* Content Source: [articles/aks/ssh.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/aks/ssh.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @yellow456434
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48285](https://github.com/MicrosoftDocs/azure-docs/issues/48285) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @yellow456434, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48285. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by VikasPullagura-MSFT** [comment]
@yellow456434 I have tried reproducing the issue, but I did not encounter any error while running the command
 `SCALE_SET_NAME=$(az vmss list --resource-group $CLUSTER_RESOURCE_GROUP --query [0].name -o tsv)`

Another suggestion is add single quotations in the command like below and see if you are running into issues while running in the shell you are trying the tutorial. 

`SCALE_SET_NAME=$(az vmss list --resource-group $CLUSTER_RESOURCE_GROUP --query '[0].name' -o tsv)`

However, requesting you to run in bash shell as I tried this in Cloud Shell and it works as expected. If you still see issues running this in bash please report back with the error message.

**Comment by VikasPullagura-MSFT** [comment]
@yellow456434 Any update on the issue?

**Comment by yellow456434** [comment]
Wow Nice!
I add single quotations It’s ok
I guess I must to add auotation because My mac terminal use zsh not bash

Thank you

從我的iPhone傳送

VikasPullagura-MSFT <notifications@github.com> 於 2020年2月19日 下午6:24 寫道：

﻿

@yellow456434<https://github.com/yellow456434> I have tried reproducing the issue, but I did not encounter any error while running the command
SCALE_SET_NAME=$(az vmss list --resource-group $CLUSTER_RESOURCE_GROUP --query [0].name -o tsv)

Another suggestion is add single quotations in the command like below and see if you are running into issues while running in the shell you are trying the tutorial.

SCALE_SET_NAME=$(az vmss list --resource-group $CLUSTER_RESOURCE_GROUP --query '[0].name' -o tsv)

However, requesting you to run in bash shell as I tried this in Cloud Shell and it works as expected. If you still see issues running this in bash please report back with the error message.

**Comment by VikasPullagura-MSFT** [comment]
@yellow456434 Thanks for confirming that issue is resolved.
