### ISSUE TITLE
 Azure 帳戶中心>設定檔>沒有 [稅務記錄]

### ISSUE THREAD

**Issue by HannahHsiao** [MicrosoftDocs/azure-docs.zh-tw#615]
如何變更統一編號？
若要新增或更新統一編號，請在 Azure 帳戶中心更新您的設定檔，然後選取 [稅務記錄] 。 此統一編號會用於計算免稅金額，並出現在您的發票上。

Azure 帳戶中心&gt;設定檔&gt;沒有 [稅務記錄]

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4fb8bd80-8dc3-94be-dc1e-7cd6428da63c
* Version Independent ID: 523e8db2-6428-6a51-b536-c3d531560aee
* Content: [變更您用於 Azure 的信用卡](https://docs.microsoft.com/zh-tw/azure/cost-management-billing/manage/change-credit-card)
* Content Source: [articles/cost-management-billing/manage/change-credit-card.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/cost-management-billing/manage/change-credit-card.md)
* Service: **cost-management-billing**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @HannahHsiao
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52402](https://github.com/MicrosoftDocs/azure-docs/issues/52402) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
您好，@HannahHsiao，  

非常感謝您的貢獻。您的意見反應與原始文件相關。  

因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/azure-docs/issues/52402。  

我們由衷感謝您對文章的貢獻。   

順頌時祺  
Microsoft DOCS 國際小組
