### ISSUE TITLE
費用

### ISSUE THREAD

**Issue by sonychen59** [MicrosoftDocs/azure-docs.zh-tw#618]
1. 照著上述這樣的步驟, 就能 12個月 都 免費 嗎?
2. 步驟上, 後續的 磁碟 網路 ... 設定 都是 預設值? 會不會 一個月後, 又要收取 額外的超出費用?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 2e58109c-c8d3-6693-8e1d-03a89ca26168
* Version Independent ID: f20a7fc4-328a-e90d-29db-92a91aa1b2bd
* Content: [快速入門 - 在 Azure 入口網站中建立 Windows VM](https://docs.microsoft.com/zh-tw/azure/virtual-machines/windows/quick-create-portal#feedback)
* Content Source: [articles/virtual-machines/windows/quick-create-portal.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/virtual-machines/windows/quick-create-portal.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by srvbpigh** [comment]
Hello, @sonychen59
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55286](https://github.com/MicrosoftDocs/azure-docs/issues/55286) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
您好，@sonychen59，  

非常感謝您的貢獻。您的意見反應與原始文件相關。  

因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/azure-docs/issues/55286。  

我們由衷感謝您對文章的貢獻。   

順頌時祺  
Microsoft DOCS 國際小組
