### ISSUE TITLE
Incorrect Chinese translation on this page

### ISSUE THREAD

**Issue by prayerful007** [MicrosoftDocs/azure-docs.zh-tw#627]
本頁的中文翻譯錯誤
There is an error in the Chinese translation of this page

English: Whereas the S1 tier handles more than 50 queries per second.
Current Chinese translation: 而 S1 層處理的每秒查詢數"不"超過50個。
Correct translation should be: 而 S1 層處理的每秒查詢數超過50個。
(with the excessive "不", the meaning is entirely opposite.)

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: a40139e7-7b9e-e3c5-4cf6-860fefdbcf79
* Version Independent ID: 768e160e-b9c5-c8ad-9d4a-56eff82ebd38
* Content: [選擇正確的定價層](https://docs.microsoft.com/zh-tw/azure/azure-maps/choose-pricing-tier)
* Content Source: [articles/azure-maps/choose-pricing-tier.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/azure-maps/choose-pricing-tier.md)
* Service: **azure-maps**
* GitHub Login: @philmea
* Microsoft Alias: **philmea**

**Comment by srvbpigh** [comment]
Hello, @prayerful007
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
@prayerful007  您好：  

感謝您的參與。  

目前不接受參與機器翻譯內容的翻譯問題。  

我們很重視您對人工翻譯內容的意見反應與建議，並使用這些意見來訓練機器翻譯引擎，因此，您的貢獻內容會隨著時間改善人工與機器翻譯的品質。  

您可以根據各個內容檔案標頭的 ms.translationtype 中繼資料值 “HT”，分辨出人工翻譯的主題，其他則是機器翻譯的主題 (值為 “MT” 代表機器翻譯)。  

非常感謝您的支援。  

Microsoft DOCS 全球體驗小組
