### ISSUE TITLE
Incorrect translation in Chinese

### ISSUE THREAD

**Issue by StellaSSHuang** [MicrosoftDocs/azure-docs.zh-tw#94]
Incorrect ：
您必須至少為一個企業或"預付"型方案訂用帳戶的「擁有者」角色。
Correct：
您必須至少為一個企業或"隨用隨付"型方案訂用帳戶的「擁有者」角色。

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: edda1fe4-6ce9-ccf2-bc1b-65e9818b1060
* Version Independent ID: 5151901d-a4d3-1148-811f-8c9a959608a3
* Content: [節省成本的 Azure 虛擬機器預付](https://docs.microsoft.com/zh-tw/azure/virtual-machines/windows/prepay-reserved-vm-instances)
* Content Source: [articles/virtual-machines/windows/prepay-reserved-vm-instances.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/virtual-machines/windows/prepay-reserved-vm-instances.md)
* Service: **virtual-machines-windows**
* Product: **unspecified**
* GitHub Login: @vikramdesai01
* Microsoft Alias: **vikdesai**

**Comment by CeciAc** [comment]
Hello, @StellaSSHuang,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @StellaSSHuang
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
