### ISSUE TITLE
LOAD DATA INFILE

### ISSUE THREAD

**Issue by 4lenz1** [MicrosoftDocs/azure-docs.zh-tw#95]
LOAD DATA INFILE：支援，但必須指定導向 UNC 路徑 (透過 XSMB 裝載的 Azure 儲存體) 的 [LOCAL] 參數。

請問這句話是什麼意思呢?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 09a85aa0-5baf-cf60-94a0-fa949c3a841b
* Version Independent ID: f3673c4b-4c84-64be-27e5-04d57f4b5008
* Content: [「適用於 MySQL 的 Azure 資料庫」中的限制](https://docs.microsoft.com/zh-tw/azure/mysql/concepts-limits)
* Content Source: [articles/mysql/concepts-limits.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/mysql/concepts-limits.md)
* Service: **mysql-database**
* GitHub Login: @kamathsun
* Microsoft Alias: **sukamat**

**Comment by CeciAc** [comment]
您好 @4lenz1

謝謝您的寶貴意見。 

我們目前正在檢閱您的留言，將會盡快與您連絡。 

順頌時祺 
Microsoft DOCS 國際小組

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10045](https://github.com/MicrosoftDocs/azure-docs/issues/10045) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
您好，@4lenz1

非常感謝您的貢獻。您的意見反應與原始文件相關。 

因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 https://github.com/MicrosoftDocs/azure-docs/issues/10045


我們由衷感謝您對文章的貢獻。  


順頌時祺 

Microsoft DOCS 國際小組
