### ISSUE TITLE
Title 'VS 程式碼' is not corrct in menu of AzureSQL Database 

### ISSUE THREAD

**Issue by matsurigoto** [MicrosoftDocs/azure-docs.zh-tw#99]
It is 'VS Code', not 'VS 程式碼'.
VS Code is a IDE name, please don't translation.

url: https://docs.microsoft.com/zh-tw/azure/sql-database/sql-database-connect-query-vscode
image url: http://bit.ly/2MGn1F2 

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4998b228-9ad4-4aa2-91a8-a5dc948975d4
* Version Independent ID: b37ea4d7-319a-67b5-f317-561f34ef2cac
* Content: [VS Code：在 Azure SQL Database 中連接和查詢資料](https://docs.microsoft.com/zh-tw/azure/sql-database/sql-database-connect-query-vscode)
* Content Source: [articles/sql-database/sql-database-connect-query-vscode.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/live/articles/sql-database/sql-database-connect-query-vscode.md)
* Service: **sql-database**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by gosali** [comment]
Hello, @matsurigoto , 

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 

Microsoft DOCS International Team

**Comment by matsurigoto** [comment]
sorry, 
Any update :) ?

**Comment by LisandroSu** [comment]
Hello, @matsurigoto   
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [VS Code：在 Azure SQL Database 中連接和查詢資料](https://docs.microsoft.com/zh-tw/azure/sql-database/sql-database-connect-query-vscode).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
